
# Spring配置1
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wy_upms?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true

# redis 配置
redis:
  # 地址
  host: localhost
  # 端口，默认为6379
  port: 6379
  # 密码
  password:
  # 连接超时时间
  timeout: 10s
  lettuce:
    pool:
      # 连接池中的最小空闲连接
      min-idle: 0
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池的最大数据库连接数
      max-active: 8
      # #连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1ms

# 日志配置
logging:
  level:
    com.ruoyi: debug
    org.springframework: warn

# MyBatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.wy.upms.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
#  mapperLocations: classpath*:mybatis/mapper/*Mapper.xml
  mapperLocations: classpath*:com/wy/upms/**/mapper/*.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8087
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30
